============================= test session starts ==============================
platform linux -- Python 3.9.14, pytest-7.1.3, pluggy-1.0.0
rootdir: /workspace
collected 14 items
tests/test_a_environment.py .                                            [  7%]
tests/test_a_setup.py .                                                  [ 14%]
tests/test_distances.py ...                                              [ 35%]
tests/test_generate_regression_data.py .                                 [ 42%]
tests/test_knn.py ....F                                                  [ 78%]
tests/test_metrics.py .                                                  [ 85%]
tests/test_polynomial_regression.py ..                                   [100%]
=================================== FAILURES ===================================
_____________________________ test_knn_regression ______________________________
>                       assert mse <= 0.1, msg
E                       AssertionError: degree=7, amount=100, k=5: 0.134 should be <= 0.1
E                       assert 0.13410809193398296 <= 0.1
tests/test_knn.py:147: AssertionError
=============================== warnings summary ===============================
tests/test_knn.py::test_knn_k_is_1
tests/test_knn.py::test_knn_k_is_1
tests/test_knn.py::test_knn_k_is_1
  /workspace/src/distances.py:90: RuntimeWarning: invalid value encountered in divide
    D = np.dot(X,Y.T)/(np.linalg.norm(Y[None, :, :], axis=-1)*np.linalg.norm(X[:, None, :], axis=-1))
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_knn.py::test_knn_regression - AssertionError: degree=7, amo...
================== 1 failed, 13 passed, 3 warnings in 34.29s ===================